-- Active: 1683550667297@@containers-us-west-105.railway.app@6565@railway

CREATE TABLE
    personal (
        `ID_DNI_C` char(8) NOT NULL,
        `CIP_C` char(9) DEFAULT NULL,
        `AP_PATERNO_V` varchar(50) DEFAULT NULL,
        `AP_MATERNO_V` varchar(50) DEFAULT NULL,
        `NOMBRE_V` varchar(191) DEFAULT NULL,
        PASSWORD_V varchar(255) NOT NULL,
        SECRET_PASS_V varchar(255) NOT NULL,
        ESTADO_B tinyint(1) DEFAULT "1",
        `FECHA_NAC_D` DATE DEFAULT NULL,
        `FOTO_V` varchar(191) DEFAULT NULL,
        `DOMIC_I` varchar(191) DEFAULT NULL,
        `CELULAR_V` varchar(191) DEFAULT NULL,
        `FECHA_CREATE_D` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `GRADO_ID_I` int NOT NULL,
        `ESPECIALIDAD_ID_I` int NOT NULL,
        PRIMARY KEY (`ID_DNI_C`),
        CONSTRAINT `FK_especialidad_id` FOREIGN KEY (`ESPECIALIDAD_ID_I`) REFERENCES `especialidad_arma` (`ID_ESP_I`) ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT `FK_grado_id` FOREIGN KEY (`GRADO_ID_I`) REFERENCES `grado` (`ID_GRADO_I`) ON DELETE RESTRICT ON UPDATE CASCADE
    );

CREATE TABLE
    personal_role (
        ID_PERSONAL_ROLE_I INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        PERSONAL_ID_C CHAR(8) NOT NULL,
        ROLE_ID_I INT,
        ESTADO_B tinyint(1) DEFAULT "1",
        FECHA_CREATE_D datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        CONSTRAINT FK_personal_id FOREIGN KEY (PERSONAL_ID_C) REFERENCES personal(ID_DNI_C) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_role_id FOREIGN KEY (ROLE_ID_I) REFERENCES role(ID_ROLE_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    `role` (
        `ID_ROLE_I` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `DESC_CORTA_V` varchar(100) NOT NULL,
        `DESC_LARGA_V` varchar(200) NOT NULL,
        `ESTADO_B` tinyint(1) DEFAULT '1'
    );

CREATE TABLE
    personal_menu (
        ID_PERSONAL_MENU_I INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        PERSONAL_ID_C CHAR(8) NOT NULL,
        MENU_ID_I INT,
        ESTADO_B tinyint(1) DEFAULT "1",
        FECHA_CREATE_D datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        CONSTRAINT FK_personal_menu_id FOREIGN KEY (PERSONAL_ID_C) REFERENCES personal(ID_DNI_C) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_menu_per_id FOREIGN KEY (MENU_ID_I) REFERENCES menu(ID_MENU_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    menu (
        `ID_MENU_I` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `DESC_CORTA_V` varchar(100) NOT NULL,
        `DESC_LARGA_V` varchar(200) NOT NULL,
        ROLE_ID_I INT NOT NULL,
        URL_OPCION VARCHAR(200) NULL,
        ICON VARCHAR(200) NULL,
        `ESTADO_B` tinyint(1) DEFAULT '1',
        CONSTRAINT FK_menu_role_id FOREIGN KEY (ROLE_ID_I) REFERENCES role(ID_ROLE_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    personal_opciones (
        ID_PERSONAL_OPCIONES_I INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        PERSONAL_ID_C CHAR(8) NOT NULL,
        OPCIONES_ID_I INT,
        ESTADO_B tinyint(1) DEFAULT "1",
        FECHA_CREATE_D datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        CONSTRAINT FK_personal_opcion_id FOREIGN KEY (PERSONAL_ID_C) REFERENCES personal(ID_DNI_C) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_opcion_perso_id FOREIGN KEY (OPCIONES_ID_I) REFERENCES opciones(ID_OPCIONES_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    opciones (
        `ID_OPCIONES_I` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `DESC_CORTA_V` varchar(100) NOT NULL,
        `DESC_LARGA_V` varchar(200) NOT NULL,
        MENU_ID_I INT NOT NULL,
        URL_OPCION VARCHAR(200) NULL,
        ICON VARCHAR(200) NULL,
        `ESTADO_B` tinyint(1) DEFAULT '1',
        CONSTRAINT FK_menu_opciones_id FOREIGN KEY (MENU_ID_I) REFERENCES menu(ID_MENU_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    personal_evaluacion (
        ID_PERSONAL_EVALUACION_I INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        PERSONAL_ID_C CHAR(8) NOT NULL,
        EVALUACION_ID_I INT NOT NULL,
        ESTADO_B tinyint(1) DEFAULT "1",
        FECHA_CREATE_D datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        CONSTRAINT FK_personal_evaluacionx_id FOREIGN KEY (PERSONAL_ID_C) REFERENCES personal(ID_DNI_C) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_evaluacion_per_id FOREIGN KEY (EVALUACION_ID_I) REFERENCES evaluacion(ID_EVALUACION_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE
    evaluacion (
        ID_EVALUACION_I INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        DESC_CORTA_V varchar(100) NOT NULL,
        DESC_LARGA_V varchar(200) NOT NULL,
        ESTADO_B tinyint(1) DEFAULT "1",
        FECHA_CREATE_D datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    );

CREATE TABLE
    preguntas (
        ID_PREGUNTA_I INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        NUMERO_PRE_I INT NOT NULL,
        PREGUNTA TEXT NOT NULL ,
        URL_IMG VARCHAR(255),
        PRE2 VARCHAR(255),
        OPCION_1 TEXT,
        OPCION_2 TEXT,
        OPCION_3 TEXT,
        OPCION_4 TEXT,
        OPCION_5 TEXT,
        RESP_CORRECTA_V TEXT,
        EVALUACION_ID_I INT NOT NULL,
        MENU_ID_I INT NOT NULL,
        OPCIONES_ID_I INT NOT NULL,
        ESTADO_B tinyint(1) DEFAULT "1",
        CONSTRAINT FK_evaluacion_pre_id FOREIGN KEY (EVALUACION_ID_I) REFERENCES evaluacion(ID_EVALUACION_I) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_menux_id FOREIGN KEY (MENU_ID_I) REFERENCES menu(ID_MENU_I) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_opcionex_id FOREIGN KEY (OPCIONES_ID_I) REFERENCES opciones(ID_OPCIONES_I) ON DELETE CASCADE ON UPDATE CASCADE
    );

DESCRIBE role;

SELECT * from personal_role;